name: Test

on:
  push:
    paths-ignore:
      - .github/**
      - go.sum

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run tests
        run: go test ./...

      - name: Run integration tests
        working-directory: integration
        run: go test
